# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f5372579befc8a653c5bae620c4f224ab295dbd499e9fbbffdc12da08a842a5222797a4d514f7e6776fac634d2a6cd49000f73088b9d25eb3b434bc20fe2ec0

test:
  secret_key_base: 73fb131cdf415ed6c7095d00be65e4e9751d84733e7f4bea411ed5e68fb9a8552699ea220115e18eb58556c336974432cf41c7580faa1d6324ff26b228d99bb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
